### ISSUE TITLE
Question: How to graceful stop docker-parity?

### ISSUE THREAD

**Issue by isLishude** [paritytech/parity-ethereum#10053]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: stable
- **Operating system**: Linux
- **Installation**: homebrew / one-line installer / built from source
docker-compose file

```yml
version: "3"

services:

  parity:
    image: "parity/parity:stable"
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
    volumes:
      - ${PWD}/.parity:/home/parity/.local
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --no-ui
      - --no-dapps
      - --no-config
      - --no-ws
      - --tracing=on
      - --auto-update=none
      - --max-peers=100
      - --jsonrpc-interface=all
      - --jsonrpc-apis=safe
      - --jsonrpc-hosts=all
      - --jsonrpc-threads=8
      - --jsonrpc-cors=all
      - --jsonrpc-server-threads=8
      - --jsonrpc-max-payload=10
      # - --tx-queue-size=8192
      # - --tx-queue-per-sender=16
      # - --tx-queue-mem-limit=4

    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
```

I setted `stop_signal: SIGINT` && `stop_grace_period: 2m` but it does not work.

- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
