### ISSUE TITLE
How to use docker-compose with https and wss protocols

### ISSUE THREAD

**Issue by XtreemSolution** [paritytech/parity-ethereum#11486]
I'm using docker-compose file to start Partiy on my server

```  
  version: '2.4'  
  services:  
    clear_parity:  
      image: parity/parity:stable
      ports:
        - "0.0.0.0:8545:8545"
        - "0.0.0.0:8546:8546"
        - "30303:30303"
        - "30303:30303/udp"
      command: --jsonrpc-interface=all --ws-origins all --ws-hosts all --ws-interface all --ui-interface=all --base-path /home/parity/.local/share/io.parity.ethereum/ --auto-update=none
      volumes:
        - /var/lib/io.parity.ethereum/chain_data/:/home/parity/.local/share/io.parity.ethereum/
```
Currenly I'm using WebSocket as 

> web3 = new Web3(new Web3.providers.WebsocketProvider("ws://ip-address:8546"));

But  it is not working on my HTTPS website, I did:

> web3 = new Web3(new Web3.providers.WebsocketProvider("wss://ip-address:8546"));

But it gives me error: 

> Firefox can’t establish a connection to the server at wss://ip-address:8546/.

So basically its a SSL error and I don't know how to add certificate in docker-compose file (I have SSL Certificates for my domains)
