### ISSUE TITLE
Error(Encrypt(\"failed to lookup address information: Name or service not known\"), State { next_error: None, backtrace: None

### ISSUE THREAD

**Issue by jackieWhn** [paritytech/parity-ethereum#9129]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 11..4 beta
> - **Which operating system?**:  Linux
> - **How installed?**: via installer  binaries 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: private 
> - **Did you try to restart the node?**:  yes

Did I missing something? 
I got this error "Error(Encrypt(\"failed to lookup address information: Name or service not known\"), State { next_error: None, backtrace: None })" when i deployed private contracts. 

**RPC Call** 
```json
{"method":"private_composeDeploymentTransaction","params":["latest", "0xf901478308161f80839896808080b8f56060604052341561000f57600080fd5b60d88061001d6000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680630c55699c146046578063bc64b76d14607457600080fd5b3415605057600080fd5b60566098565b60405180826000191660001916815260200191505060405180910390f35b3415607e57600080fd5b6096600480803560001916906020019091905050609e565b005b60005481565b8060008160001916905550505600a165627a7a723058206acbdf4b15ca4c2d43e1b1879b830451a34f1e9d02ff1f2f394d8d857e79d2080029824669a0fc509ee8812acf4969f3533ec4eaa78464be6bf2856813da275b4d35daba7428a066e2275d7bfac14f12cccfe317a492d1be702000d25b88f74c59e1fb95276ee8", ["0x22******66"], "0x0"],"id":1,"jsonrpc":"2.0"}
```
**Error**
```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32024,
    "message": "Private transactions call failed.",
    "data": "Error(Encrypt(\"failed to lookup address information: Name or service not known\"), State { next_error: None, backtrace: None })"
  },
  "id": 1
}
```
**Here is my config file**
```toml
[parity]
chain = "contract-product-spec.json"
base_path = "./chainData/networks/parity0"

[network]
reserved_peers = "reservedPeers.enode"
reserved_only = true
port = 30316

[rpc]
interface = "0.0.0.0"
port = 8556
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts","private"]

[websockets]
interface = "0.0.0.0"
port = 8546
origins = ["all"]
hosts = ["all"]

[ui]
interface = "0.0.0.0"
port = 8196
hosts = ["all"]

[mining]
engine_signer = "0x22****66"
reseal_max_period = 300000
usd_per_tx = "0"
gas_floor_target = "50000000"

[secretstore]
disable = false
nodes = []
http_interface = "local"
http_port = 8082
interface = "local"
port = 8083
path = "./chainData/networks/parity0/secretstore"

[private_tx]
enabled = true
validators = ["0x22*****66"]
account = "0x22*****66"
sstore_url = "http://secretstore:8082"
passwords ="node.pwds"
```
