### ISSUE TITLE
Parity on Kubernetes

### ISSUE THREAD

**Issue by onpaws** [paritytech/parity-ethereum#9218]
> I'm running:
>
> - **Which Parity version?**: [2.0.0](https://github.com/paritytech/parity-ethereum/releases/tag/v2.0.0)
> - **Which operating system?**: Linux as provided by the Docker image
> - **How installed?**: Docker image installed via Kubernetes
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: kovan
> - **Did you try to restart the node?**: yes

I have a "Parity on Kubernetes" security question and would appreciate any insight.

I've deployed the Parity k8n manifests @ddorgan shared [here](https://github.com/paritytech/parity-ethereum/issues/7288#issuecomment-393500569) -- they've been working great, thanks!
I see the logs on the Parity pod show syncing to the blockchain - excellent.

I also see the Kubernetes docs indicate services of type `ClusterIP` "makes the service only reachable from within the cluster."
Now, because I see the blockchain syncing in the logs I think they mean something like a traditional NAT setup - traffic originating inside my Pod can get out, but originating outside the cluster won't route to the Service/Pod.

OK, so far so good.

Enter my app, which is Dockerized, and depends on the Parity JSON-RPC. I know I shouldn't open JSON-RPC to the outside world. At home, I know NAT on my router should prevent direct connections to my machines behind the router. 

Thus I believe, but am not 100% sure, it should be safe to run Parity under a service as follows. 
What do you think?

```
apiVersion: v1
kind: Service
metadata:
  name: parity-service
  namespace: default
spec:
  selector:
    app: parity
  ports:
    - name: eth-net
      port: 30303
      protocol: TCP
    - name: json-rpc-http
      port: 8545
      protocol: TCP
    - name: json-rpc-ws
      port: 8546
      protocol: TCP
```

**Comment by JohnnySheffield** [comment]
I think the traffic on 30303 should be UDP, not TCP so something like:

```
 ports:
    - name: eth-net
      port: 30303
      protocol: UDP
    ...
```
But it would be best if somebody can confirm this.

Be it tcp or udp, your DockerFile must expose this port so your service can target it, eg:

`EXPOSE 8080 8545 8180 30303/udp`

I'm also not sure what would be the best practice - generally what ports should be exposed on Parity docker images? 

Related to #9231
