### ISSUE TITLE
PoA nodes are no longer transmitting transactions to other (mining)-nodes

### ISSUE THREAD

**Issue by roderik** [paritytech/parity-ethereum#9329]
> I'm running:
>
> - **Which Parity version?**: 2.0.1
> - **Which operating system?**: Docker on Linux
> - **How installed?**: Offcial Docker image
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: PoA network, details below
> - **Did you try to restart the node?**: yes

> Network info
>
> - **Spec file**: https://github.com/settlemint/mintnet/blob/master/mintnet.json
> - **Stats**: https://stats.mintnet.settlemint.com/
> - **Explorer**: https://explorer.mintnet.settlemint.com/

> Network setup:
>
> - 2 mining nodes in 2 regions in Digital Ocean (with firewall around it, but due to debugging allows all traffic) - Bootnodes config
> - 2 edge nodes (non-mining) with a load balancer in front with an https connection URL (like you use infura) - Bootnodes config
> - Each project or dev machine runs a client docker node to read and write to - Client config

> Bootnodes:
>
> - **Commandline**: https://gist.github.com/roderik/97dd56161db1a75f0022a071b0abaaa3
> - **Config**: https://gist.github.com/roderik/67a63642d3ffae8661deefc7061f5c70
> - **Dockerfile**: https://gist.github.com/roderik/5867da2fb08ca43af58ac3bbb658fc73
> - **Docker container**: not public

> Clients:
>
> - **Commandline**: https://github.com/settlemint/mintnet/blob/master/entrypoint.sh
> - **Config**: https://github.com/settlemint/mintnet/blob/master/mintnet.toml
> - **Dockerfile**: https://github.com/settlemint/mintnet/blob/master/Dockerfile
> - **Docker container**: https://hub.docker.com/r/settlemint/mintnet/

## Actual and Expected behavior with v2.0.0 and below

This setup ran smoothly. Transactions were sent to either the client or edge nodes and processed by the mining nodes every 5 seconds.

## Actual behavior after upgrading everything to v2.0.1

* Sending a transaction to a client node, will import the TX nicely but does not transmit it to the rest of the nodes. So the miners never pick up on them. 
* Sending a transaction to the load balancer or an edge node directly, same behavior
* Sending a transaction to a mining node, will mine a block with the transaction in it.

* Changes made: https://github.com/settlemint/mintnet/compare/2.0.0...master (lots of debugging tries so do not mind the commit mess)
* Edge node logs with a lot of tracing enabled: https://gist.github.com/roderik/17897483ca68be04f659e97e224a63c6 (look for tx id 0x9e792fd35d277627c268119113d3168be5eb599417d821e28012fbb2467af594)
* Client node logs with less tracing enabled: https://gist.github.com/roderik/ba6078f14d0f412ca478ea0159e0d4cb (look for tx id 0xe48675d399ac2b5d3d9e05ea0f326a3187da13ccf6041a03dc4a4edce7b16f98)

What is weird:

1. Four nodes, 10 peers? Peer list from [an edge node](https://gist.github.com/roderik/24f12c2ee44caa2bb99710b79fb364ee) and from [a miner node](https://gist.github.com/roderik/2d274c7787987a26f1efaed817a709ca). Starting a client makes it go to 11. Why are there a bunch of 1.11.3 nodes connection or a non-standard port with a custom network id?
2. Sending a tx to an edge node ends up with a stuck tx with e.g txid 0xe48675d399ac2b5d3d9e05ea0f326a3187da13ccf6041a03dc4a4edce7b16f98 on the edge node (so 1 pending). Sending that same transaction (executing another migration.sol deployment) to the mining node, which ends up with the same txid, goes in, gets mined, and then the client does drop the pending one. So there is communication between the nodes, just not "sending".

I've got a workaround, I pointed my load balancer to the mining node, but that is not in the least decentralized nor resilient. I've got no further ideas on what it could be, the only thing I have not tried is rolling everything back to 2.0.0, but since I've found no issues relating to the same problem, I guess it's more a config issue on my end than a software issue.

**Comment by Tbaut** [comment]
Do you have any way to reproduce on a minimal setup for us to reproduce quickly? This would tremendously help :)

**Comment by roderik** [comment]
Use this docker-compose file https://github.com/settlemint/mintnet/blob/master/docker-compose.yml and a client node will spin up and start syncing. After the sync, you can send a tx to it.

The easiest way to send a TX is by running `ETHEREUM_DEPLOYER_SEED='robot robot robot robot robot robot robot robot robot robot robot robot' truffle migrate --network mintnet` on https://github.com/DataBrokerDAO/dtx-crowdsale-contracts 

Adding more logging to the container can be done by cloning https://github.com/settlemint/mintnet , changing either the toml or the entrypoint.sh file and modifying the docker-compose file as follows

```
version: "3.3"

services:
  ethereum:
    build: .
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
  net-intelligence-api:
    image: settlemint/eth-net-intelligence-api
    environment:
      CONTACT_DETAILS: i-support@mintnet.com
      INSTANCE_NAME: My awesome Node (add a company name or location)
      LISTENING_PORT: '30311'
      RPC_HOST: ethereum
      RPC_PORT: '8545'
      WS_SECRET: settlemint
      WS_SERVER: wss://stats.mintnet.settlemint.com
    links:
      - ethereum:ethereum
```

then run `docker-compose build; docker-compose up`.
