### ISSUE TITLE
docker parity keeps crashing 

### ISSUE THREAD

**Issue by grigored** [paritytech/parity-ethereum#9810]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 0.0.0
- **Operating system**: Amazon Linux
- **Installation**: docker
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I'm starting parity using the following simple docker-compose configuration.
```
  ethnode:
    image: parity/parity:stable
    volumes:
    - /home/ec2-user/nodeData/ethData:/root/.local/share/io.parity.ethereum
    command: --unsafe-expose --ui-no-validation --chain=foundation --mode=active --no-ws --no-ipc --pruning=fast --pruning-memory=2000 --min-peers=25 --max-peers=50
``` 

Yet every few minutes the container is killed and has to restart syncing. I only see this in logs:
```
2018-10-25 12:01:32 UTC Syncing #6578024 0x93b8…3142     1.22 blk/s   99.4 tx/s    8 Mgas/s      0+  562 Qed  #6578587    5/25 peers      5 MiB chain    2 GiB db   47 MiB queue   13 MiB sync  RPC:  0 conn,    0 req/s,    0 µs
./entrypoint.sh: line 2:     6 Killed                  parity $@
```

How do I get parity to work?
